# Generated by Django 3.1.4 on 2020-12-03 16:21

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnoUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('user_type', models.CharField(choices=[('STORE', 'STORE'), ('PRODUCTION', 'PRODUCTION'), ('ADMIN', 'ADMIN')], max_length=10)),
            ],
            options={
                'verbose_name': 'TechnoUser',
                'verbose_name_plural': 'TechnoUsers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
