# Generated by Django 3.1.4 on 2021-01-03 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlloyMaster',
            fields=[
                ('alloy_name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('alloy_class', models.CharField(choices=[('PIPE', 'PIPE'), ('MGO', 'MGO'), ('CONDUCTOR', 'CONDUCTOR')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ElementMaster',
            fields=[
                ('metal_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('lot_number', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('supplier_name', models.TextField(blank=True, null=True)),
                ('alloy_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.alloymaster')),
            ],
        ),
        migrations.CreateModel(
            name='PipeAlloyElementQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('element_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.elementmaster')),
                ('pipe_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.pipe')),
            ],
            options={
                'unique_together': {('pipe_obj', 'element_obj')},
            },
        ),
        migrations.CreateModel(
            name='PipeAlloyElementMappingMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alloy_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.alloymaster')),
                ('element_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.elementmaster')),
            ],
            options={
                'unique_together': {('alloy_obj', 'element_obj')},
            },
        ),
    ]
