# Generated by Django 3.1.4 on 2021-01-03 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0002_alloymaster_elementmaster_pipe_pipealloyelementmappingmaster_pipealloyelementquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MGO',
            fields=[
                ('lot_number', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supplier_name', models.TextField(blank=True, null=True)),
                ('alloy_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.alloymaster')),
            ],
        ),
        migrations.CreateModel(
            name='MGOAlloyElementQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('element_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.elementmaster')),
                ('mgo_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.mgo')),
            ],
            options={
                'unique_together': {('mgo_obj', 'element_obj')},
            },
        ),
        migrations.CreateModel(
            name='MGOAlloyElementMappingMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alloy_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.alloymaster')),
                ('element_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.elementmaster')),
            ],
            options={
                'unique_together': {('alloy_obj', 'element_obj')},
            },
        ),
    ]
