# Generated by Django 3.1.4 on 2021-01-03 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0003_mgo_mgoalloyelementmappingmaster_mgoalloyelementquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('lot_number', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supplier_name', models.TextField(blank=True, null=True)),
                ('alloy_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.alloymaster')),
            ],
        ),
        migrations.CreateModel(
            name='ConductorAlloyElementQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('negative_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('conductor_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.conductor')),
                ('element_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.elementmaster')),
            ],
            options={
                'unique_together': {('conductor_obj', 'element_obj')},
            },
        ),
        migrations.CreateModel(
            name='ConductorAlloyElementMappingMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_min_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('positive_max_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('negative_min_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('negative_max_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('alloy_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.alloymaster')),
                ('element_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.elementmaster')),
            ],
            options={
                'unique_together': {('alloy_obj', 'element_obj')},
            },
        ),
    ]
