# Generated by Django 3.1.4 on 2021-01-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0004_conductor_conductoralloyelementmappingmaster_conductoralloyelementquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductoralloyelementmappingmaster',
            name='negative_max_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='conductoralloyelementmappingmaster',
            name='negative_min_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
