# Generated by Django 3.1.4 on 2021-01-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0005_auto_20210103_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductoralloyelementquantity',
            name='negative_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
