# Generated by Django 3.1.4 on 2021-01-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0006_auto_20210103_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('item_code', models.TextField(blank=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coil',
            fields=[
                ('coil_number', models.IntegerField(primary_key=True, serialize=False)),
                ('mgo_qty', models.DecimalField(decimal_places=2, max_digits=5)),
                ('conductor_qty', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pipe_qty', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(default='In Production')),
                ('conductor_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.conductor')),
                ('item_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.itemmaster')),
                ('mgo_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.mgo')),
                ('pipe_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.pipe')),
            ],
        ),
    ]
