# Generated by Django 3.1.4 on 2021-04-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0007_coil_itemmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coil',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='coil',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='coil',
            name='status',
        ),
        migrations.AlterField(
            model_name='coil',
            name='conductor_qty',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='coil',
            name='mgo_qty',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='qty',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='conductoralloyelementmappingmaster',
            name='negative_max_percent',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='conductoralloyelementmappingmaster',
            name='negative_min_percent',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='conductoralloyelementmappingmaster',
            name='positive_max_percent',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='conductoralloyelementmappingmaster',
            name='positive_min_percent',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='conductoralloyelementquantity',
            name='negative_quantity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='conductoralloyelementquantity',
            name='positive_quantity',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mgo',
            name='qty',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='mgoalloyelementmappingmaster',
            name='max_percent',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mgoalloyelementmappingmaster',
            name='min_percent',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mgoalloyelementquantity',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pipealloyelementmappingmaster',
            name='max_percent',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pipealloyelementmappingmaster',
            name='min_percent',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pipealloyelementquantity',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.CreateModel(
            name='CoilStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status_class', models.CharField(choices=[('PRODUCTION', 'PRODUCTION'), ('ENALING', 'ENALING'), ('DRAW', 'DRAW')], max_length=10)),
                ('coil_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.coil')),
            ],
        ),
    ]
