# Generated by Django 3.1.4 on 2021-04-02 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0011_auto_20210402_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilstatus',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='coilstatus',
            unique_together={('coil_number', 'status_class')},
        ),
    ]
