# Generated by Django 3.1.4 on 2021-04-02 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0012_auto_20210402_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilstatus',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
