# Generated by Django 3.1.4 on 2021-04-02 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0013_auto_20210402_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilstatus',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
