# Generated by Django 3.1.4 on 2021-04-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0015_auto_20210402_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='coil',
            name='coil_diameter',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='coilstatus',
            name='coil_diameter',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coilstatus',
            name='status_class',
            field=models.CharField(choices=[('ANNEALING', 'ANNENALING'), ('DRAW', 'DRAW')], default='DRAW', max_length=15),
        ),
    ]
