# Generated by Django 3.1.4 on 2021-04-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0016_auto_20210404_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='diameter',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipe',
            name='diameter',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
