# Generated by Django 3.1.4 on 2021-04-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0017_auto_20210404_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawBenchMaster',
            fields=[
                ('draw_bench_name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FurnaceMaster',
            fields=[
                ('furnace_name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='coilstatus',
            name='status_class',
            field=models.CharField(choices=[('ANNEALING', 'ANNENALING'), ('DRAW', 'DRAW')], max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='coilstatus',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coilstatus',
            name='draw_bench_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.drawbenchmaster'),
        ),
        migrations.AddField(
            model_name='coilstatus',
            name='furnace_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TechnoApp.furnacemaster'),
        ),
    ]
