# Generated by Django 3.1.4 on 2021-04-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0018_auto_20210404_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilstatus',
            name='status_class',
            field=models.CharField(choices=[('ANNEALING', 'ANNEALING'), ('DRAW', 'DRAW')], max_length=15),
        ),
    ]
