# Generated by Django 3.1.4 on 2021-04-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0019_auto_20210404_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilstatus',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
