# Generated by Django 3.1.4 on 2021-04-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoApp', '0020_auto_20210411_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilstatus',
            name='coil_diameter',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
    ]
